name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        playwright-version: ["1.14", "1.15", "1.16", "1.17", "1.18", "next"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm install @playwright/test@${{ matrix.playwright-version }}
    - run: npx playwright install --with-deps
    - run: npx playwright test .
